find-your-college-app/config/routes.rb
Rails.application.routes.draw do
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'students#welcome'

get 'signin', to: "students#signin"

get 'home', to: "students#home"

get 'signout', to: "students#signout"

post 'signin', to: "students#after_signin"

get 'search', to: "students#search"
post 'search', to: "students#match"
get 'match', to: "students#showmatch"

get 'application', to: "students#application"
post 'applications', to: "students#home"
get 'applications', to: "students#home"

get 'showapplication', to: "applications#showapplication"

end

find-your-college-app/app/models/activity.rb
class Activity < ApplicationRecord
    has_many :college_activities
    has_many :student_activities
    # has_many :students, through: student_activities
    # has_many :colleges, through: college_activities
end

find-your-college-app/app/models/application.rb
class Application < ApplicationRecord
    belongs_to :student
    belongs_to :college
end

find-your-college-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

find-your-college-app/app/models/college.rb
class College < ApplicationRecord
    has_many :applications
    has_many :college_activities
    has_many :activities, through: :college_activities
end

find-your-college-app/app/models/college_activity.rb
class CollegeActivity < ApplicationRecord
    belongs_to :college
    belongs_to :activity
end

find-your-college-app/app/models/student.rb
class Student < ApplicationRecord
    has_many :applications
    has_many :student_activities
    has_many :activities, through: :student_activities

  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
end

find-your-college-app/app/models/student_activity.rb
class StudentActivity < ApplicationRecord
    belongs_to :activity
    belongs_to :student
end

find-your-college-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

find-your-college-app/app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

    def showapplication
        @student = Student.find(session[:student_id])
    end
end

find-your-college-app/app/controllers/students_controller.rb
require 'digest/sha1'

class StudentsController < ApplicationController

def welcome
end

def signin
end

def after_signin
    @student = Student.find_by(username: params[:username])
    if @student.valid?
        session[:student_id] = @student.id
    redirect_to home_path
    else flash[:messages] = @student.errors.full_messages
        redirect_to signin_path
    end
end 

def home
    @student = Student.find(session[:student_id])
end

def signout
    reset_session
    flash[:info] = "Signed out suuccessfully!"
    redirect_to root_path
end

def new
    @student = Student.new
end

def create
    @student = Student.create(student_params)
    if @student.valid? 
        session[:student_id] = @student.id
    redirect_to home_path
    else flash[:messages] = @student.errors.full_messages
        redirect_to new_student_path
    end
end

def edit
    @student = Student.find(params[:id])
end

def update
    @student = Student.update(params[:id], student_params)
    if @student.valid? 
        redirect_to home_path
        else flash[:messages] = @student.errors.full_messages
            redirect_to edit_student_path
        end
end

def destroy
    reset_session
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to root_path
end

def search 
    @student = Student.find(session[:student_id])
    @activities = Activity.all
end

def match
    count = [College.first,0,0]
    fixedParams = []
    params["name"][1..].each do |i|
        StudentActivity.create(student_id:session[:student_id], activity_id:i)
        fixedParams << CollegeActivity.find_by(activity_id: Activity.find(i.to_i))
    end
    College.all.each do |college|
        CollegeActivity.where(college_id:college.id).each do |activity|
            if fixedParams.include?(activity)
                count[2] += 1
            end
        end
        if count[2] > count[1]
            count[0] = college
        end
        count[2] = 0
    end
    session[:college_id] = count[0].id
    redirect_to match_path
end

def showmatch
    @college = College.find(session[:college_id])
end

def application
    @college = College.find(params["format"])
    @student = Student.find(session[:student_id])
    @application = Application.new
    @activities = @student.activities
end

private

def student_params
    params.require(:student).permit(:name, :GPA, :high_school, :username)
end


end

find-your-college-app/app/helpers/activities_helper.rb
module ActivitiesHelper
end

find-your-college-app/app/helpers/application_helper.rb
module ApplicationHelper
end

find-your-college-app/app/helpers/applications_helper.rb
module ApplicationsHelper
end

find-your-college-app/app/helpers/college_activities_helper.rb
module CollegeActivitiesHelper
end

find-your-college-app/app/helpers/colleges_helper.rb
module CollegesHelper
end

find-your-college-app/app/helpers/student_activities_helper.rb
module StudentActivitiesHelper
end

find-your-college-app/app/helpers/students_helper.rb
module StudentsHelper
end

find-your-college-app/app/views/applications/showapplication.html.erb
<h1> <%= @student.name%>'s Submitted Applications </h2>

<% @student.applications.each do |application|%>
<%= application.name %>
<% end %>

<%= button_to "Start a New Search", search_path(@student), method: :get %>


<%= link_to "Back to Home", home_path %>

find-your-college-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindYourCollegeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel=“stylesheet” href=“https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css”>
  <script src=“https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js”></script>
  <script src=“https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js”></script>
  <script src=“https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js”></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="welcome-page">
  
    <%= yield %>
  </body>
</html>

find-your-college-app/app/views/students/_form.html.erb
<% if flash[:messages] %>
  <h2>Errors</h2>
  <ul>
    <% flash[:messages].each do |error| %>
      <li><%= error %> </li>
    <% end%>
  </ul>
<% end%>
<ul>
<%= form_for @student do |f| %>
    <br> Full Name: <%= f.text_field :name %> </br>
    <br> Username: <%= f.text_field :username %> </br>
    <br> High School: <%= f.text_field :high_school %> </br>
    <br> Your current GPA: <%= f.number_field :GPA, step: :any %> </br>
    <br> <%= f.submit %> </br>
    <% end %>
</ul>





    

find-your-college-app/app/views/students/application.html.erb
<h1> Application for: <%= @college.name%> </h1>

<h2> <%= @student.name%>'s Information: </h2>
<%= @student.name %>
<%= @student.high_school %>
<%= @student.GPA %> 
<% @activities.each do |activity| %>
<%= activity.name %>
<% end %>

<%= form_for @application do |f| %>
<%= f.label :resume%>
<%= f.file_field :resume%>
<%= f.submit %>
<% end %>

find-your-college-app/app/views/students/edit.html.erb
<h1> Edit Student </h1>

<%= render "form" %>

find-your-college-app/app/views/students/home.html.erb
<h1> Your Student Home Page </h1>

<%= button_to "Search", search_path(@student), method: :get %>
<%= button_to "Applications", showapplication_path(@application), method: :get %>
<%= button_to "Edit", edit_student_path(@student), method: :get %>
<%= button_to "Delete", student_path(@student), method: :delete %>
<%= button_to "Sign Out", signout_path(@student), method: :get %>

find-your-college-app/app/views/students/new.html.erb
<ul>
<h1> Student Sign Up Form </h1>
</ul>

<%= render "form" %>

find-your-college-app/app/views/students/search.html.erb
<h1> Search Colleges </h1>

<%= form_with(url:search_path, method: "post") do |f| %>
    <% @activities.map{|activity| activity.category}.uniq.each do |category| %>
        <h2> <%=category%></h2>
        <%= f.collection_select :name, @activities.where(category:category), :id, :name, {:include_bank => ""}, {:multiple => true}%>
    <% end %>
    <%= f.submit %>
<% end %>

find-your-college-app/app/views/students/showmatch.html.erb
<h1> Your matching College </h1>
<h2> <%= @college.name%> </h2>

<h3> Apply here: </h3>
<%= button_to @college.name, application_path(@college), method: :get %>

find-your-college-app/app/views/students/signin.html.erb
<ul>
<h1> Student Sign In Page </h1>
</ul>

<%= form_tag signin_path do |f| %>
    <div class="field">
    <%= label_tag :username %>
    <%= text_field_tag :username %>
    </div>

    <div class="actions">
    <%= submit_tag "Sign In" %>
    </div>

    <% end %>

find-your-college-app/app/views/students/welcome.html.erb
<div>
    <ul>
    <h1> Welcome to 'Find Your College' </h1>
    </ul>


    Already have an account? <br> <%= link_to "Sign In", signin_path %> </br>
    <br> <%= link_to "Sign Up", new_student_path %> </br>

</div>